export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST';
export const CHECK_TASK_TODO_LIST = 'CHECK_TASK_TODO_LIST';
export const UPDATE_TASK_TODO_LIST = 'CLOSE_TASK_TODO_LIST';
export const UPDATE_PERFORM_TASK_TODO_LIST = 'UPDATE_PERFORM_TASK_TODO_LIST';
