export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST';
export const CHECK_TASK_TODO_LIST = 'REMOVE_TODO_LIST';
export const CLOSE_TASK_TODO_LIST = 'CLOSE_TASK_TODO_LIST';
